name: Bump Chart Version

on:
  workflow_dispatch:
    inputs:
      chart-version:
        description: 'The new chart version'
        required: true
        type: string
      skip-version-validation:
        description: 'Should skip chart version validation'
        required: true
        default: false
        type: boolean
  workflow_call:
    inputs:
      chart-version:
        description: 'The new chart version'
        required: true
        type: string
      skip-version-validation:
        description: 'Should skip chart version validation'
        required: true
        default: false
        type: boolean
    secrets:
      token:
        description: 'The github token to use to create the PR'
        required: true

jobs:
  update-app-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v4.1.0
        with:
          version: v3.12.1

      - name: Validate version
        if: ${{ !inputs.skip-version-validation }}
        run: |
          helm repo add spot https://charts.spot.io
          helm repo update

          if [[ $(helm search repo spot/ocean-kubernetes-controller --version ${{ inputs.chart-version }}) == "No results found" ]]; then
            echo "Chart version ${{ inputs.chart-version }} not found in the repository"
            exit 1
          fi

      - name: Update version
        uses: actions/github-script@v7
        env:
          NEW_VERSION: ${{ inputs.chart-version }}
        with:
          script: |
            const fs = require('fs');
            const file = fs.readFileSync('variables.tf', 'utf8');
            const lines = file.split('\n');
            const chartVersionLine = lines.findIndex(line => line.includes('chart_version'));
            const versionLine = lines.findIndex((line, i) => line.includes('default') && i > chartVersionLine);
            const oldVersion = lines[versionLine].match(/"([^"]+)"/)[1];
            const newVersion = process.env.NEW_VERSION;
            lines[versionLine] = lines[versionLine].replace(oldVersion, newVersion);
            fs.writeFileSync('variables.tf', lines.join('\n'));
            console.log(`updated version from ${oldVersion} to ${newVersion}`);

      - name: Generate version bump commit
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -a -m "chore: bump chart version to '${{ inputs.chart-version }}'"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ github.token }}
          title: '[bump] chart - ${{ inputs.chart-version }}'
          branch: bump/chart_${{ inputs.chart-version }}
          delete-branch: true
          labels: auto_version_bump
