name: Create Release
on:
  push:
    branches:
      - main
    paths:
      - './VERSION'

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Get the next version
      id: next-version
      run: echo "VALUE=$(cat VERSION)" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.next-version.outputs.VALUE }}
        release_name: ${{ steps.next-version.outputs.VALUE }}
        draft: false
        commitish: main # use the latest commit on main branch (including the new version)
        prerelease: false
